# Generated by Django 4.1 on 2023-03-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apd_name', models.CharField(max_length=64, unique=True)),
                ('template_roles', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_name', models.TextField(max_length=1000)),
                ('modality', models.TextField(max_length=1000)),
                ('predicate', models.TextField(max_length=1000)),
                ('condition', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyBigTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apd_name', models.TextField(max_length=1000)),
                ('modality', models.TextField(max_length=1000)),
                ('predicate', models.TextField(max_length=1000)),
                ('condition', models.TextField(max_length=1000)),
                ('RegulationSource', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=1000)),
                ('documents', models.FileField(upload_to='document/')),
                ('consent_artefact', models.JSONField(blank=True, null=True)),
                ('resource_apd', models.TextField(max_length=1000)),
                ('resource_inode', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
