# Generated by Django 4.1.3 on 2023-03-10 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consent_service', '0002_template_user_role_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='apd',
            name='apd_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User Id'),
        ),
    ]
