# Generated by Django 4.1 on 2023-03-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0003_apd_apd_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
    ]
