# Generated by Django 4.1.7 on 2023-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0004_remove_resource_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='consent_artefact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
