# Generated by Django 4.1.7 on 2023-03-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0005_alter_resource_consent_artefact'),
    ]

    operations = [
        migrations.AddField(
            model_name='policybigtable',
            name='condition_type',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
