# Generated by Django 4.1.7 on 2023-03-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0006_policybigtable_condition_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policybigtable',
            old_name='RegulationSource',
            new_name='action',
        ),
    ]
