# Generated by Django 4.1.7 on 2023-03-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0007_rename_regulationsource_policybigtable_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policybigtable',
            name='action',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
