# Generated by Django 4.1.7 on 2023-03-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0008_alter_policybigtable_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='action',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
