# Generated by Django 4.1.7 on 2023-03-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0009_jurisdiction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='policybigtable',
            name='RegulationSource',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
