# Generated by Django 4.1.7 on 2023-03-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0010_policybigtable_regulationsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='docutment_type',
            field=models.TextField(null=True),
        ),
    ]
