# Generated by Django 4.1.7 on 2023-03-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0011_resource_docutment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='docutment_type',
        ),
        migrations.AddField(
            model_name='resource',
            name='document_type',
            field=models.TextField(null=True),
        ),
    ]
