# Generated by Django 4.1.7 on 2023-04-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0012_remove_resource_docutment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policybigtable',
            old_name='condition_type',
            new_name='artifact',
        ),
        migrations.RemoveField(
            model_name='policybigtable',
            name='predicate',
        ),
        migrations.AddField(
            model_name='policybigtable',
            name='event',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='policybigtable',
            name='event_type',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='policybigtable',
            name='condition',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='policybigtable',
            name='modality',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
