# Generated by Django 4.1 on 2023-06-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consent_service", "0014_remove_jurisdiction_jurisdiction_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="policybigtable", old_name="RegulationSource", new_name="Source",
        ),
        migrations.AddField(
            model_name="jurisdiction",
            name="Source",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
