# Generated by Django 4.1 on 2023-07-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consent_service",
            "0015_rename_regulationsource_policybigtable_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="document_name",
            field=models.TextField(null=True),
        ),
    ]
