# Generated by Django 4.1.7 on 2023-08-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0016_resource_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.TextField(max_length=100)),
                ('statements', models.TextField(max_length=2000)),
                ('modality', models.TextField(default='N', max_length=50)),
            ],
        ),
    ]
